// AUTO-GENERATED by tools/canvas-cli-jianying-core.mjs — DO NOT EDIT.
// 源码是页面剪映导出的纯函数层 apps/web/libs/jianying/*.ts（唯一真相源），这里是它打成的零依赖 ESM 单文件。
// 改导出逻辑请改源码，再运行 `node tools/canvas-cli-jianying-core.mjs` 重新生成；
// tests/studio/jianying-cli-core.test.ts 会重新打包并与本文件逐字节比对。
//#region apps/web/libs/video-editor/episodes.ts
var UNKNOWN_EPISODE = "unknown";
/** Keep editor grouping and Jianying export on the same title convention. */
function episodeKey(title) {
	const digits = /(?:^|[^a-z0-9])ep([0-9]+)/i.exec(title)?.[1];
	if (!digits) return UNKNOWN_EPISODE;
	return `EP${digits.replace(/^0+(?=\d)/, "").padStart(2, "0")}`;
}
function episodeKeys(clips) {
	return [...new Set(clips.map((clip) => episodeKey(clip.title)))].sort((a, b) => {
		if (a === "unknown") return 1;
		if (b === "unknown") return -1;
		return a.length - b.length || a.localeCompare(b);
	});
}
//#endregion
//#region apps/web/libs/jianying/types.ts
/** 素材在草稿包里的相对目录（POSIX 写法，落盘时按 pathSep 换）。 */
var JIANYING_ASSET_DIR = "assets/video";
/** 主视频轨的轨道名，剪映界面上直接显示它。 */
var JIANYING_MAIN_TRACK_NAME = "主视频轨";
var JIANYING_DRAFT_VERSION = 36e4;
var JIANYING_NEW_VERSION = "110.0.0";
var JIANYING_APP_VERSION = "5.9.0";
var JIANYING_APP_ID = 3704;
var DEFAULT_DRAFT_RATIO = "9:16";
/** 只认这三种容器；.webm / 无扩展名一律在预检阶段拒掉，一个字节都不下。 */
var JIANYING_VIDEO_EXTENSIONS = /* @__PURE__ */ new Set([
	".mp4",
	".mov",
	".m4v"
]);
/** **每个工程**的片段数上限。按集导出时每集各算各的，整批导出的总段数不设上限。 */
var JIANYING_MAX_CLIPS = 200;
/** 按集导出时「没有集号」那一组工程的标签，与剪辑器里那个选项卡同名。 */
var JIANYING_OTHER_PROJECT_LABEL = "其他";
/** 最短片段 100ms，= `MIN_VIDEO_CLIP_MS * 1000`，与编辑器的裁剪下限同源。 */
var MIN_JIANYING_SEGMENT_US = 1e5;
/** AssetHub 直连的并发。 */
var DIRECT_FETCH_CONCURRENCY = 4;
var MEDIA_FETCH_ATTEMPTS = 3;
/**
* 预检失败一律走这个类型，`message` 必须是能直接贴进界面的中文原因。
* 裸 `Error` 会让浮层只能显示「导出失败」，那等于没告诉用户任何事。
*/
var JianyingExportError = class extends Error {
	constructor(reason, message, clipTitle, options) {
		super(message, options);
		this.reason = reason;
		this.clipTitle = clipTitle;
		this.name = "JianyingExportError";
	}
};
//#endregion
//#region apps/web/libs/jianying/canvas-size.ts
/**
* 草稿画布尺寸。三级优先（规格 §2.5）：
*   ① 用户在浮层里的显式覆写 → canvasFromRatio；
*   ② 无覆写 → 实测尺寸里出现次数最多的那一个（并列取时间线第一段），偶数化后直接用；
*   ③ 一个都测不出 → 9:16。
*
* 落到草稿里只影响 canvas_config.width/height 与顶层 fps；canvas_config.ratio
* 恒为字符串 "original"，那是 buildEmptyDraft 写死的，跟这里的 ratio 字段无关
* （这里的 ratio 只给界面显示用）。
*/
/** 剪映不接受奇数边长；四舍五入到最近的偶数。 */
function even(n) {
	return Math.round(n / 2) * 2;
}
/** 比例字符串 → 短边 1080 的画布。认不出的比例退回竖屏 9:16。迁自 jianying-export.mjs:527-539。 */
function canvasFromRatio(ratio) {
	const match = String(ratio || "").trim().match(/^(\d+(?:\.\d+)?)\s*[:：xX×]\s*(\d+(?:\.\d+)?)$/u);
	let w = 9;
	let h = 16;
	if (match && Number(match[1]) > 0 && Number(match[2]) > 0) {
		w = Number(match[1]);
		h = Number(match[2]);
	}
	const short = 1080;
	if (w >= h) return {
		width: even(short * w / h),
		height: short,
		fps: 30,
		ratio: `${w}:${h}`
	};
	return {
		width: short,
		height: even(short * h / w),
		fps: 30,
		ratio: `${w}:${h}`
	};
}
/**
* 实测尺寸 → 画布。`measurements` 必须按时间线顺序给（一段一条，同源用两次就出现两次），
* 众数并列时取先出现的那个 —— 「时间线第一段」这条兜底靠的就是这个顺序。
*
* 众数尺寸偶数化后**直接用**，不再按短边重算：`ratio: "original"` 说明宽高本身
* 就是权威值，1920×1080 就该写 1920×1080。
*/
function canvasFromMeasurements(measurements, override) {
	if (override) return canvasFromRatio(override);
	const counts = /* @__PURE__ */ new Map();
	for (const item of measurements) {
		const width = Number(item?.width);
		const height = Number(item?.height);
		if (!Number.isFinite(width) || !Number.isFinite(height) || width <= 0 || height <= 0) continue;
		const key = `${width}x${height}`;
		const seen = counts.get(key);
		if (seen) seen.count += 1;
		else counts.set(key, {
			width,
			height,
			count: 1
		});
	}
	let best = null;
	for (const candidate of counts.values()) if (!best || candidate.count > best.count) best = candidate;
	if (!best) return canvasFromRatio(DEFAULT_DRAFT_RATIO);
	const width = even(best.width);
	const height = even(best.height);
	return {
		width,
		height,
		fps: 30,
		ratio: `${width}:${height}`
	};
}
/** `X:\…` 或 `X:/…`。盘符后面必须有分隔符：`C:foo` 是「C 盘当前目录下的 foo」，不是绝对路径。 */
var WINDOWS_DRIVE_RE = /^[A-Za-z]:[\\/]/u;
/** UNC：`\\server\share…`，服务器名与共享名都得有。 */
var WINDOWS_UNC_RE = /^\\\\[^\\/]+[\\/]+[^\\/]+/u;
/** 这条路径是不是 Windows 形状（盘符或 UNC）。 */
function isWindowsDraftRootPath(path) {
	const value = String(path ?? "");
	return WINDOWS_DRIVE_RE.test(value) || WINDOWS_UNC_RE.test(value);
}
/**
* 这条路径该用哪个分隔符。
*
* **从路径本身推，不看浏览器 UA**：用户完全可能在 Mac 上给同事配一条 Windows 路径，
* 也完全可能在 Windows 的浏览器里导一份要拷到 Mac 上的草稿。UA 是「谁在点按钮」，
* 草稿根是「文件要落到哪台机器」，这是两件事。
* （顺带把 `platformInfo` 的 `os` 也修对了 —— 它从前也是跟着 UA 跑的。）
*/
function draftRootPathSep(path) {
	return isWindowsDraftRootPath(path) ? "\\" : "/";
}
/**
* 去掉首尾空白与结尾的分隔符，好让 `/a/b` 与 `/a/b/` 是同一条（去重也靠它）。
* 根本身留着：`/` 去成空串、`C:\` 去成 `C:`（那是「C 盘当前目录」，语义都变了）。
*/
function normalizeDraftRootPath(raw) {
	let path = typeof raw === "string" ? raw.trim() : "";
	while (path.length > 1 && (path.endsWith("/") || path.endsWith("\\"))) {
		const next = path.slice(0, -1);
		if (/^[A-Za-z]:$/u.test(next)) break;
		path = next;
	}
	return path;
}
/**
* 两条路径是不是**同一个地方**的判据（去重、白名单比对都用它，不许各写一遍）：规范化之后，
* Windows 形状（盘符 / UNC）不分大小写、`/` 与 `\` 算同一个分隔符、连着的分隔符算一个 ——
* `D:\JianyingPro\Drafts`、`d:/jianyingpro/drafts/` 是同一条；POSIX 路径只并掉连着的 `/`，
* **区分大小写**（macOS 默认不分，但 Linux 分；宁可多登记一条，也不把两个目录当成一个）。
* 只用来比，不拿来存：存下来的永远是用户写的那一种写法。
*/
function draftRootKey(raw) {
	const path = normalizeDraftRootPath(raw);
	if (!isWindowsDraftRootPath(path)) return path.replace(/\/{2,}/gu, "/");
	const unc = /^[\\/]{2}/u.test(path);
	const body = path.replace(/[\\/]+/gu, "\\");
	return (unc ? `\\${body}` : body).toLowerCase();
}
/** 规范化之后的路径能不能用；`null` = 能用。 */
function checkDraftRootPath(raw) {
	const path = normalizeDraftRootPath(raw);
	if (!path) return "empty";
	if (path.length > 400) return "too-long";
	if (path.startsWith("/")) return null;
	return isWindowsDraftRootPath(path) ? null : "not-absolute";
}
/**
* `<草稿根><sep><片段…>`。片段一律按 POSIX 写法传进来（`assets/video/x.mp4`），
* 由这里按草稿根的形状换成目标机的分隔符。
*/
function joinDraftPath(root, ...segments) {
	const base = normalizeDraftRootPath(root);
	const sep = draftRootPathSep(base);
	const parts = segments.flatMap((segment) => segment.split(/[\\/]/u)).filter(Boolean);
	if (parts.length === 0) return base;
	return (base.endsWith(sep) ? base : base + sep) + parts.join(sep);
}
/** 排序与挤掉用的时间值：没有 / 读不出 = 最久（负无穷）。 */
function usedAtMs(root) {
	const ms = Date.parse(root.lastUsedAt ?? "");
	return Number.isFinite(ms) ? ms : Number.NEGATIVE_INFINITY;
}
/**
* 按「最近用过的在前」排好的一份（新数组，不动原来的）。没有 `lastUsedAt` 的排在最后，彼此之间
* 保持原来的顺序。CLI `jianying-roots` 列给用户选的就是这个顺序。
*/
function sortDraftRootsByRecentUse(roots) {
	return roots.map((root, index) => ({
		root,
		index,
		ms: usedAtMs(root)
	})).sort((a, b) => a.ms === b.ms ? a.index - b.index : b.ms - a.ms).map(({ root }) => root);
}
//#endregion
//#region apps/web/libs/jianying/draft-schema.ts
/**
* 剪映草稿 JSON 的形状 —— 纯函数，迁自 script-to-video 的
* `.pi/lib/jianying-export.mjs:713-967`（那一版已经在真机上被剪映打开过）。
*
* 这里的每一个字段名、每一个常量都是「剪映能不能打开这个草稿」的凭证，
* **一个字都不许改**：`version: 360000`、`new_version: "110.0.0"`、`app_id: 3704`、
* `canvas_config.ratio: "original"`、`draft_agency_config.json` 里拼错的
* `marterials`（那是剪映自己的键名）。
*
* 随机数与时间全部走注入的 seam（`newHexId` / `newUpperId` / `now`），
* 否则这一层没法被 vitest 逐字节断言。
*/
/** Windows 剪映 5.x 读它。 */
var DRAFT_CONTENT_FILE = "draft_content.json";
/** macOS 读它，内容与 draft_content.json **同一个 stringify 字符串**。 */
var DRAFT_INFO_FILE = "draft_info.json";
/** 剪映首页卡片认这个文件夹是草稿的依据，**必须最后写**。 */
var DRAFT_META_FILE = "draft_meta_info.json";
var ATTACHMENT_PC_COMMON_FILE = "attachment_pc_common.json";
var DRAFT_AGENCY_CONFIG_FILE = "draft_agency_config.json";
var DRAFT_BIZ_CONFIG_FILE = "draft_biz_config.json";
var DRAFT_SETTINGS_FILE = "draft_settings";
var TEMPLATE_TMP_FILE = "template.tmp";
var TEMPLATE_2_TMP_FILE = "template-2.tmp";
var DRAFT_INFO_BAK_FILE = "draft_info.json.bak";
/** 32 位小写 hex，剪映内部对象 id 的形状。 */
function newHexId() {
	return globalThis.crypto.randomUUID().replace(/-/gu, "");
}
/** 大写带横线的 UUID，草稿 id 的形状。 */
function newUpperId() {
	return globalThis.crypto.randomUUID().toUpperCase();
}
/** 与 fs-safe.mjs 的 writeJsonAtomic 逐字节一致：缩进 2 + 末尾换行。 */
function draftJsonText(value) {
	return `${JSON.stringify(value, null, 2)}\n`;
}
function emptyMaterials() {
	return {
		ai_translates: [],
		audio_balances: [],
		audio_effects: [],
		audio_fades: [],
		audio_track_indexes: [],
		audios: [],
		beats: [],
		canvases: [],
		chromas: [],
		color_curves: [],
		digital_humans: [],
		drafts: [],
		effects: [],
		flowers: [],
		green_screens: [],
		handwrites: [],
		hsl: [],
		images: [],
		log_color_wheels: [],
		loudnesses: [],
		manual_deformations: [],
		masks: [],
		material_animations: [],
		material_colors: [],
		multi_language_refs: [],
		placeholders: [],
		plugin_effects: [],
		primary_color_wheels: [],
		realtime_denoises: [],
		shapes: [],
		smart_crops: [],
		smart_relights: [],
		sound_channel_mappings: [],
		speeds: [],
		stickers: [],
		tail_leaders: [],
		text_templates: [],
		texts: [],
		time_marks: [],
		transitions: [],
		video_effects: [],
		video_trackings: [],
		videos: [],
		vocal_beautifys: [],
		vocal_separations: []
	};
}
/**
* `os` 从 `pathSep` 推，而 `pathSep` 现在从**用户选定的草稿根**推（`draftRootPathSep`）
* ——反斜杠只可能来自 Windows。从前它跟着浏览器 UA 跑，于是「在 Mac 上给同事导一份
* Windows 草稿」会写出 `os: "mac"`；换成跟草稿根之后这个字段顺带也对了。
* `os_version` 桌面版填 os.release()，页面侧拿不到，留空串（剪映不读它，那是上报字段）。
*/
function platformInfo(pathSep = "/") {
	return {
		app_id: JIANYING_APP_ID,
		app_source: "lv",
		app_version: JIANYING_APP_VERSION,
		os: pathSep === "\\" ? "windows" : "mac",
		os_version: ""
	};
}
function makeEmptyDraft(canvas, draftId, pathSep) {
	const platform = platformInfo(pathSep);
	return {
		canvas_config: {
			height: canvas.height,
			ratio: "original",
			width: canvas.width
		},
		color_space: 0,
		config: {
			adjust_max_index: 1,
			attachment_info: [],
			combination_max_index: 1,
			export_range: null,
			extract_audio_last_index: 1,
			lyrics_recognition_id: "",
			lyrics_sync: true,
			lyrics_taskinfo: [],
			maintrack_adsorb: true,
			material_save_mode: 0,
			multi_language_current: "none",
			multi_language_list: [],
			multi_language_main: "none",
			multi_language_mode: "none",
			original_sound_last_index: 1,
			record_audio_last_index: 1,
			sticker_max_index: 1,
			subtitle_keywords_config: null,
			subtitle_recognition_id: "",
			subtitle_sync: true,
			subtitle_taskinfo: [],
			system_font_list: [],
			video_mute: false,
			zoom_info_params: null
		},
		cover: null,
		create_time: 0,
		duration: 0,
		extra_info: null,
		fps: canvas.fps,
		free_render_index_mode_on: false,
		group_container: null,
		id: draftId,
		keyframe_graph_list: [],
		keyframes: {
			adjusts: [],
			audios: [],
			effects: [],
			filters: [],
			handwrites: [],
			stickers: [],
			texts: [],
			videos: []
		},
		last_modified_platform: platform,
		materials: emptyMaterials(),
		mutable_config: null,
		name: "",
		new_version: JIANYING_NEW_VERSION,
		platform,
		relationships: [],
		render_index_track_mode_on: true,
		retouch_cover: null,
		source: "default",
		static_cover_image_path: "",
		time_marks: null,
		tracks: [],
		update_time: 0,
		version: JIANYING_DRAFT_VERSION
	};
}
/**
* 空草稿。字段顺序也照抄——`draft_content.json` 与 `draft_info.json` 要逐字节相同，
* 顺序一变快照就变。
*/
function buildEmptyDraft(canvas, draftId, pathSep = "/") {
	return makeEmptyDraft(canvas, draftId, pathSep);
}
/**
* 一条 materials.videos 记录。`durationUs` 是**源文件全长**，不是裁剪后长度。
*
* `path` 由 `build-draft.ts` 决定形状（客户端路线是宿主机绝对路径，zip 降级路线是草稿
* 文件夹内的相对路径）；这一层只负责把它逐字放进 `path` 字段。
*/
function buildVideoMaterial(input) {
	const id = input.newHexId();
	return {
		id,
		json: {
			audio_fade: null,
			category_id: "",
			category_name: "local",
			check_flag: 63487,
			crop: {
				upper_left_x: 0,
				upper_left_y: 0,
				upper_right_x: 1,
				upper_right_y: 0,
				lower_left_x: 0,
				lower_left_y: 1,
				lower_right_x: 1,
				lower_right_y: 1
			},
			crop_ratio: "free",
			crop_scale: 1,
			duration: input.durationUs,
			height: input.height,
			id,
			local_material_id: "",
			material_id: id,
			material_name: input.fileName,
			media_path: "",
			path: input.path,
			remote_url: null,
			type: "video",
			width: input.width
		}
	};
}
/**
* 一条轨道片段 + 它自己的 speed。
*
* 签名相对桌面版改了：`sourceStartUs` 是新的。桌面版写死 `source_timerange.start = 0`
* 是因为文件树版每个镜头都整段用；画布片段带裁剪，写死就等于把用户的每一刀都丢了。
*/
function buildVideoSegment(input) {
	const speedId = input.newHexId();
	return {
		speed: {
			curve_speed: null,
			id: speedId,
			mode: 0,
			speed: 1,
			type: "speed"
		},
		segment: {
			enable_adjust: true,
			enable_color_correct_adjust: false,
			enable_color_curves: true,
			enable_color_match_adjust: false,
			enable_color_wheels: true,
			enable_lut: true,
			enable_smart_color_adjust: false,
			last_nonzero_volume: 1,
			reverse: false,
			track_attribute: 0,
			track_render_index: 0,
			visible: true,
			id: input.newHexId(),
			material_id: input.materialId,
			target_timerange: {
				start: input.targetStartUs,
				duration: input.durationUs
			},
			common_keyframes: [],
			keyframe_refs: [],
			source_timerange: {
				start: input.sourceStartUs,
				duration: input.durationUs
			},
			speed: 1,
			volume: input.volume ?? 1,
			extra_material_refs: [speedId],
			clip: {
				alpha: 1,
				flip: {
					horizontal: false,
					vertical: false
				},
				rotation: 0,
				scale: {
					x: 1,
					y: 1
				},
				transform: {
					x: 0,
					y: 0
				}
			},
			uniform_scale: {
				on: true,
				value: 1
			},
			hdr_settings: {
				intensity: 1,
				mode: 1,
				nits: 1e3
			},
			render_index: 0
		}
	};
}
/**
* 一条转场素材。`meta` 来自转场表（`transitions.ts`），`durationUs` 来自片段上的
* `transitionOut.durationMs`。转场不改任何片段的 `target_timerange` / `source_timerange`：
* 两段照旧首尾相接，剪映在接缝处叠化。
*/
function buildTransitionMaterial(input) {
	return {
		category_id: "",
		category_name: "",
		duration: input.durationUs,
		effect_id: input.effectId,
		id: input.newHexId(),
		is_overlap: input.isOverlap,
		name: input.name,
		platform: "all",
		resource_id: input.resourceId,
		type: "transition"
	};
}
/** 字幕字号（`styles[].size` 与 `font_size` 同一个值），照 multilang-srt 写 8。 */
var SUBTITLE_FONT_SIZE = 8;
/** 字幕行距（`line_spacing`），照 multilang-srt 写 0.02（pyJianYingDraft：0.02 + 界面行距 × 0.05）。 */
var SUBTITLE_LINE_SPACING = .02;
/**
* 一条字幕的文本素材（`materials.texts` 的一条，`type: "subtitle"`）。字段逐个照 multilang-srt 的
* `textMaterial()`（`9ca3ebe:lib/jianying.mjs:45-66`）：白字（fill `[1,1,1]`）、黑色描边
* （strokes `[0,0,0]`、宽 0.08）、字号 8、居中（`alignment: 1`），每行最宽 0.82 屏宽。
*
* 只改了一处：`check_flag` 写 15 而不是 7。pyJianYingDraft（text_segment.py:386-393）的位定义里
* 描边要置 8 才生效（7 | 8 = 15）；照抄 7 的话「黑边」可能根本不显示。这一项要真机确认。
*
* `range` 按 Unicode 码点数（`[...text].length`），与 multilang-srt / pyJianYingDraft 一致。
*/
function buildSubtitleMaterial(input) {
	const text = input.text;
	return {
		add_type: 0,
		alignment: 1,
		background_alpha: 1,
		background_color: "",
		background_height: .14,
		background_horizontal_offset: 0,
		background_round_radius: 0,
		background_style: 0,
		background_vertical_offset: 0,
		background_width: .14,
		base_content: "",
		bold_width: 0,
		border_alpha: 1,
		border_color: "#000000",
		border_width: .08,
		caption_template_info: {
			category_id: "",
			category_name: "",
			effect_id: "",
			is_new: false,
			path: "",
			request_id: "",
			resource_id: "",
			resource_name: "",
			source_platform: 0
		},
		check_flag: 15,
		combo_info: { text_templates: [] },
		content: JSON.stringify({
			styles: [{
				fill: {
					alpha: 1,
					content: {
						render_type: "solid",
						solid: {
							alpha: 1,
							color: [
								1,
								1,
								1
							]
						}
					}
				},
				font: {
					id: "",
					path: ""
				},
				range: [0, [...text].length],
				size: SUBTITLE_FONT_SIZE,
				bold: false,
				italic: false,
				underline: false,
				strokes: [{
					content: {
						render_type: "solid",
						solid: {
							alpha: 1,
							color: [
								0,
								0,
								0
							]
						}
					},
					width: .08
				}]
			}],
			text
		}),
		fixed_height: -1,
		fixed_width: -1,
		font_category_id: "",
		font_category_name: "",
		font_id: "",
		font_name: "",
		font_path: "",
		font_resource_id: "",
		font_size: SUBTITLE_FONT_SIZE,
		font_source_platform: 0,
		font_team_id: "",
		font_title: "none",
		font_url: "",
		fonts: [],
		force_apply_line_max_width: false,
		global_alpha: 1,
		group_id: "",
		has_shadow: false,
		id: input.newHexId(),
		initial_scale: 1,
		inner_padding: -1,
		is_rich_text: false,
		italic_degree: 0,
		ktv_color: "",
		language: "",
		layer_weight: 1,
		letter_spacing: 0,
		line_feed: 1,
		line_max_width: .82,
		line_spacing: SUBTITLE_LINE_SPACING,
		multi_language_current: "none",
		name: "",
		original_size: [],
		preset_category: "",
		preset_category_id: "",
		preset_has_set_alignment: false,
		preset_id: "",
		preset_index: 0,
		preset_name: "",
		recognize_task_id: "",
		recognize_type: 0,
		relevance_segment: [],
		shadow_alpha: .9,
		shadow_angle: -45,
		shadow_color: "",
		shadow_distance: 5,
		shadow_point: {
			x: .6363961030678928,
			y: -.6363961030678928
		},
		shadow_smoothing: .45,
		shape_clip_x: false,
		shape_clip_y: false,
		style_name: "",
		sub_type: 0,
		subtitle_keywords: null,
		subtitle_template_original_fontsize: 0,
		text_alpha: 1,
		text_color: "#FFFFFF",
		text_curve: null,
		text_preset_resource_id: "",
		text_size: 30,
		text_to_audio_ids: [],
		tts_auto_update: false,
		type: "subtitle",
		typesetting: 0,
		underline: false,
		underline_offset: .22,
		underline_width: .05,
		use_effect_default_color: true,
		words: {
			end_time: [],
			start_time: [],
			text: []
		}
	};
}
/** 字幕在画面上的纵向位置（半个画布高为 1，-0.8 = 靠底）。剪映自己导入的字幕也是这个值。 */
var SUBTITLE_TRANSFORM_Y = -.8;
/**
* 重叠字幕分出的相邻两条文本轨之间隔**一行**（半个画布高为 1）：字号 × 字高系数 × 行高，行高按
* 1.2 倍字高（常见字体的行框）加剪映的行距（`line_spacing`，以字高计）。字号 8 时 = 0.1952。
*/
var SUBTITLE_LANE_STEP_Y = SUBTITLE_FONT_SIZE * .02 * 1.22;
/** 文本段的 render_index 从这里起编（multilang-srt 的写法，文本压在视频之上）。 */
var SUBTITLE_RENDER_INDEX_BASE = 15e3;
/**
* 第 `lane` 条文本轨（从 0 数）上字幕的纵向位置：第 0 条在底部（-0.8），每多一条上移一行，
* 同一时刻重叠的字幕就不会在同一位置叠字。取 4 位小数，免得浮点尾巴写进草稿。
*/
function subtitleLaneTransformY(lane) {
	return Math.round((SUBTITLE_TRANSFORM_Y + lane * SUBTITLE_LANE_STEP_Y) * 1e4) / 1e4;
}
/**
* 文本轨上的一段字幕。时间都是**时间轨**时间（微秒）；`source_timerange` 照 multilang-srt 从 0 起。
* `lane` = 它在第几条文本轨（从 0 数），决定纵向位置（`subtitleLaneTransformY`）。
*/
function buildTextSegment(input) {
	return {
		caption_info: null,
		cartoon: false,
		clip: {
			alpha: 1,
			flip: {
				horizontal: false,
				vertical: false
			},
			rotation: 0,
			scale: {
				x: 1,
				y: 1
			},
			transform: {
				x: 0,
				y: subtitleLaneTransformY(input.lane)
			}
		},
		common_keyframes: [],
		enable_adjust: true,
		enable_color_curves: true,
		enable_color_match_adjust: false,
		enable_color_wheels: true,
		enable_lut: true,
		enable_smart_color_adjust: false,
		extra_material_refs: [],
		group_id: "",
		hdr_settings: {
			intensity: 1,
			mode: 1,
			nits: 1e3
		},
		id: input.newHexId(),
		intensifies_audio: false,
		is_placeholder: false,
		is_tone_modify: false,
		keyframe_refs: [],
		last_nonzero_volume: 1,
		material_id: input.materialId,
		render_index: input.renderIndex,
		responsive_layout: {
			enable: false,
			horizontal_pos_layout: 0,
			size_layout: 0,
			target_follow: "",
			vertical_pos_layout: 0
		},
		reverse: false,
		source_timerange: {
			duration: input.durationUs,
			start: 0
		},
		speed: 1,
		target_timerange: {
			duration: input.durationUs,
			start: input.targetStartUs
		},
		template_id: "",
		template_scene: "default",
		track_attribute: 0,
		track_render_index: 0,
		uniform_scale: {
			on: true,
			value: 1
		},
		visible: true,
		volume: 1
	};
}
/** draft_meta_info.json。`nowUs` 是**微秒纪元**（Date.now() * 1000）。 */
function buildDraftMeta(input) {
	return {
		cloud_package_completed_time: "",
		draft_cloud_capcut_purchase_info: "",
		draft_cloud_last_action_download: false,
		draft_cloud_materials: [],
		draft_cloud_purchase_info: "",
		draft_cloud_template_id: "",
		draft_cloud_tutorial_info: "",
		draft_cloud_videocut_purchase_info: "",
		draft_cover: "",
		draft_deeplink_url: "",
		draft_enterprise_info: {
			draft_enterprise_extra: "",
			draft_enterprise_id: "",
			draft_enterprise_name: "",
			enterprise_material: []
		},
		draft_fold_path: input.draftDir,
		draft_id: input.draftId,
		draft_is_ai_packaging_used: false,
		draft_is_ai_shorts: false,
		draft_is_ai_translate: false,
		draft_is_article_video_draft: false,
		draft_is_from_deeplink: "false",
		draft_is_invisible: false,
		draft_materials: [
			0,
			1,
			2,
			3,
			6,
			7,
			8
		].map((type) => ({
			type,
			value: []
		})),
		draft_materials_copied_info: [],
		draft_name: input.draftName,
		draft_new_version: "",
		draft_removable_storage_device: "",
		draft_root_path: input.draftRoot,
		draft_segment_extra_info: [],
		draft_timeline_materials_size_: input.bytes,
		draft_type: "",
		tm_draft_cloud_completed: "",
		tm_draft_cloud_modified: 0,
		tm_draft_create: input.nowUs,
		tm_draft_modified: input.nowUs,
		tm_draft_removed: 0,
		tm_duration: input.durationUs
	};
}
/**
* 除 draft_content.json / draft_info.json 之外的 8 个文件（内容，不写盘）。
*
* `template.tmp` / `template-2.tmp` / `draft_info.json.bak` 三个是**同一份**空草稿，
* 且用的是**另一个 draftId**（照抄 jianying-export.mjs:936）。
*/
function buildSidecarFiles(input) {
	const empty = draftJsonText(buildEmptyDraft(input.canvas, input.newUpperId(), input.pathSep));
	const nowSeconds = Math.floor(input.nowMs / 1e3);
	return {
		[DRAFT_META_FILE]: draftJsonText(buildDraftMeta({
			draftDir: input.draftDir,
			draftRoot: input.draftRoot,
			draftName: input.draftName,
			draftId: input.draftId,
			durationUs: input.durationUs,
			bytes: input.bytes,
			nowUs: input.nowMs * 1e3
		})),
		[ATTACHMENT_PC_COMMON_FILE]: draftJsonText({
			ai_packaging_infos: [],
			ai_packaging_report_info: {
				caption_id_list: [],
				task_id: "",
				text_style: "",
				tos_id: "",
				video_category: ""
			},
			commercial_music_category_ids: [],
			pc_feature_flag: 0,
			recognize_tasks: [],
			template_item_infos: [],
			unlock_template_ids: []
		}),
		[DRAFT_AGENCY_CONFIG_FILE]: draftJsonText({
			marterials: null,
			use_converter: false,
			video_resolution: 720
		}),
		[DRAFT_BIZ_CONFIG_FILE]: "",
		[DRAFT_SETTINGS_FILE]: `[General]\ndraft_create_time=${nowSeconds}\ndraft_last_edit_time=${nowSeconds}\nreal_edit_keys=0\nreal_edit_seconds=0\n`,
		[TEMPLATE_TMP_FILE]: empty,
		[TEMPLATE_2_TMP_FILE]: empty,
		[DRAFT_INFO_BAK_FILE]: empty
	};
}
//#endregion
//#region apps/web/libs/jianying/file-names.ts
/**
* 草稿包里一切「名字」的唯一出处：草稿文件夹名、素材文件名、包内相对路径的校验。
*
* 纯函数，不碰 node:path —— 页面侧根本没有它，而包内路径本来也只认 `/`
* （那既是 zip 条目名的写法，也是 Windows 文件 API 吃得下的写法）。
*/
/** 素材落盘名的形状；`assetFileName` 自己产出后再核一遍，防的是摘要函数被换掉。 */
var ASSET_FILE_NAME_RE = /^\d{3}_[0-9a-f]{8}\.(mp4|mov|m4v)$/;
/** Windows 保留设备名：叫这个名字的文件在 NTFS 上根本建不出来。 */
var WINDOWS_RESERVED_RE = /^(con|prn|aux|nul|com[1-9]|lpt[1-9])(\..*)?$/i;
/**
* 文件夹名里不能有的字符全部去掉；Windows 还不允许以点或空格结尾。
* 迁自 jianying-export.mjs:199-207，只多加一次「截断之后再去一次尾部点/空格」——
* 原版是先去尾再 slice(0,80)，第 80 个字符正好是点或空格时会把它重新暴露出来。
*/
function safeName(value, fallback = "剪映工程") {
	return String(value || "").replace(/[<>:"/\\|?*\u0000-\u001f]/gu, "").replace(/\s+/gu, " ").trim().replace(/[. ]+$/gu, "").slice(0, 80).replace(/[. ]+$/gu, "") || fallback;
}
/** 本地时区的 `YYYYMMDD_HHmmss`。迁自 jianying-export.mjs:919-922。 */
function localTimestamp(date = /* @__PURE__ */ new Date()) {
	const pad = (value) => String(value).padStart(2, "0");
	return `${date.getFullYear()}${pad(date.getMonth() + 1)}${pad(date.getDate())}_${pad(date.getHours())}${pad(date.getMinutes())}${pad(date.getSeconds())}`;
}
/** 工程标签（`EP01` / `其他`）的长度上限：集号的位数不设限，别让它把剧名挤没了。 */
var MAX_PROJECT_LABEL = 24;
/**
* 草稿文件夹名 = 安全化的剧名 [+ `_<工程标签>`] + 本地时间戳。
*   · 单工程：`<剧名>_20260923_101500`
*   · 按集：  `<剧名>_EP01_20260923_101500`、`<剧名>_其他_20260923_101500`
*
* **时间戳是唯一的防重名手段**：页面看不见磁盘，做不了「已经有同名文件夹就改成 _2」
* 那种避让；而用户在剪映里精剪过的工程，绝不能被下一次导出解压覆盖。所以要给标签与时间戳
* 预留位置：这个名字下游还会再过一次 `safeName`（plan.ts 把它当成普通名字消毒），而
* safeName 会 slice(0, 80)。剧名一长，第二次截断正好把 `_EP01_YYYYMMDD_HHmmss` 削掉——
* 那时同一天的两次导出会解压到同一个目录，把上一份改过的草稿覆盖掉。
*/
function draftFolderName(projectName, date, label) {
	const stamp = localTimestamp(date);
	const tag = label ? safeName(label, "").slice(0, MAX_PROJECT_LABEL).replace(/[. ]+$/gu, "") : "";
	const suffix = `${tag ? `_${tag}` : ""}_${stamp}`;
	return `${safeName(projectName).slice(0, 80 - suffix.length).replace(/[. ]+$/gu, "") || safeName(null)}${suffix}`;
}
/**
* URL 末段的扩展名，只认剪映吃得下的容器；别的（含无扩展名、`.webm`）返回 null，
* 由调用方拒整单。查询串与 hash 先剥掉——AssetHub 的签名 URL 带 `?x-oss-...`。
*/
function extensionFromUrl(url) {
	const base = (String(url || "").split(/[?#]/u)[0] ?? "").split(/[\\/]/u).pop() ?? "";
	const dot = base.lastIndexOf(".");
	if (dot <= 0) return null;
	const ext = base.slice(dot).toLowerCase();
	return JIANYING_VIDEO_EXTENSIONS.has(ext) ? ext : null;
}
/**
* 素材落盘名：`001_a3f91c2e.mp4`。
*
* **永不取自 clip.title** —— title 是 agent/用户可控的任意非空字符串，带 `/`、`..`、`:`
* 就能逃出 assets/video/，或在 Windows 上撞 NTFS 备用数据流与保留名。序号取该 key
* **首次**出现在时间线里的位置，保证剪映素材面板的排序与时间线一致。
*/
function assetFileName(ordinal, key, url, hash) {
	const ext = extensionFromUrl(url);
	if (!ext) throw new JianyingExportError("unsupported-container", `剪映只认 ${[...JIANYING_VIDEO_EXTENSIONS].join(" / ")}，这个素材的地址是「${url}」。`);
	const digest = String(hash(key)).toLowerCase().slice(0, 8);
	const name = `${String(ordinal).padStart(3, "0")}_${digest}${ext}`;
	if (!ASSET_FILE_NAME_RE.test(name)) throw new JianyingExportError("unsupported-container", `素材名「${name}」不符合剪映草稿的命名规则，导出已中止。`);
	return name;
}
/**
* 草稿包内相对路径（`files` 的键，也就是 zip 条目名）的校验器：按 `/` 分段后逐段禁空段、
* `.`、`..`、非法字符、结尾点或空格、Windows 保留名。
*/
function isSafeDraftRelPath(key) {
	if (!key || key.startsWith("/") || key.endsWith("/")) return false;
	if (/[\\:*?"<>|\u0000-\u001f]/u.test(key)) return false;
	return key.split("/").every((segment) => segment.length > 0 && segment !== "." && segment !== ".." && !/[. ]$/u.test(segment) && !WINDOWS_RESERVED_RE.test(segment));
}
//#endregion
//#region apps/web/libs/jianying/subtitles.ts
/**
* 读一段的 `subtitles`（不可信输入）。规则与存盘时的 `sanitizeTimeline` 一致：文本为空、时间
* 不是非负有限数、结束不晚于开始的条目丢掉（剪映里显示不出来的东西不写）。毫秒 → 微秒。
*/
function planSubtitles(raw) {
	if (!Array.isArray(raw)) return [];
	const cues = [];
	for (const item of raw) {
		if (!item || typeof item !== "object") continue;
		const { text, startMs, endMs } = item;
		if (typeof text !== "string" || !text.trim()) continue;
		if (typeof startMs !== "number" || typeof endMs !== "number") continue;
		if (!Number.isFinite(startMs) || !Number.isFinite(endMs) || startMs < 0) continue;
		const startUs = Math.round(startMs * 1e3);
		const endUs = Math.round(endMs * 1e3);
		if (endUs <= startUs) continue;
		cues.push({
			text,
			startUs,
			endUs
		});
	}
	return cues;
}
/**
* 逐段截取、换算，然后分轨：返回的每一项是一条文本轨上的字幕（按时间轨时间排好、互不重叠）。
* 没有任何能显示的字幕时返回空数组 —— 调用方据此不建文本轨。
*/
function layoutSubtitleTracks(placements, minDurUs) {
	const cues = [];
	for (const placement of placements) {
		const sourceEndUs = placement.sourceStartUs + placement.durUs;
		for (const cue of placement.subtitles ?? []) {
			const from = Math.max(cue.startUs, placement.sourceStartUs);
			const to = Math.min(cue.endUs, sourceEndUs);
			if (to - from < minDurUs) continue;
			cues.push({
				text: cue.text,
				startUs: placement.targetStartUs + (from - placement.sourceStartUs),
				durUs: to - from
			});
		}
	}
	const ordered = cues.map((cue, index) => ({
		cue,
		index
	})).sort((a, b) => a.cue.startUs - b.cue.startUs || a.index - b.index).map(({ cue }) => cue);
	const tracks = [];
	const trackEnds = [];
	for (const cue of ordered) {
		let lane = trackEnds.findIndex((end) => end <= cue.startUs);
		if (lane < 0) {
			lane = tracks.length;
			tracks.push([]);
			trackEnds.push(0);
		}
		tracks[lane].push(cue);
		trackEnds[lane] = cue.startUs + cue.durUs;
	}
	return tracks;
}
//#endregion
//#region apps/web/libs/jianying/transitions.ts
/**
* 转场表：时间线上的类型键 → 剪映转场素材。加一种转场 = 在这里加一行，并在
* `VideoCutTransitionType` 里加一个字面量。
*
* 叠化取自 pyJianYingDraft 的转场元数据表（GuanYixuan/pyJianYingDraft@c3318066，
* `pyJianYingDraft/metadata/transition_meta.py:49`，Apache-2.0）：
* `TransitionMeta("叠化", False, "6724845717472416269", "322577", "2d641adc…", 0.500, True)`
* —— 免费（非 VIP）、默认 0.5 秒、`is_overlap: true`。这组 id 只有这一个来源，要在剪映 5.9
* 真机上验证（见 docs/integrations/jianying-draft-export.md 的验证清单）。
*/
var JIANYING_TRANSITIONS = { dissolve: {
	name: "叠化",
	resourceId: "6724845717472416269",
	effectId: "322577",
	isOverlap: true
} };
/** 时间线上允许写的转场类型（报错时原样列给写入方看）。 */
var SUPPORTED_TRANSITION_TYPES = ["cut", ...Object.keys(JIANYING_TRANSITIONS)];
var TYPE_LABELS = {
	cut: "硬切",
	dissolve: "叠化"
};
function supportedList() {
	return SUPPORTED_TRANSITION_TYPES.map((type) => TYPE_LABELS[type] ? `${type}（${TYPE_LABELS[type]}）` : type).join("、");
}
function invalid(label, why) {
	return new JianyingExportError("invalid-transition", `片段「${label}」的出场转场${why}`, label);
}
/**
* 读一段的 `transitionOut`（不可信输入：agent 写的、协作者写的、旧数据）。
* 缺省 / 硬切 → `null`；合法的剪映转场 → 规划用的形状（微秒）；其余一律拒，不静默改成硬切。
*
* 调用方只对「有下一段」的片段调用：最后一段的值直接忽略，不校验。
*/
function planTransitionOut(raw, label) {
	if (raw === void 0 || raw === null) return null;
	if (typeof raw !== "object" || Array.isArray(raw)) throw invalid(label, `不是 { type, durationMs } 的形状，导不出去。支持的类型：${supportedList()}。`);
	const { type, durationMs } = raw;
	if (typeof type !== "string" || !SUPPORTED_TRANSITION_TYPES.includes(type)) throw invalid(label, `类型「${String(type)}」剪映导出不支持。支持的类型：${supportedList()}。`);
	if (typeof durationMs !== "number" || !Number.isFinite(durationMs)) throw invalid(label, `时长「${String(durationMs)}」不是一个合法的毫秒数。`);
	if (type === "cut") {
		if (durationMs !== 0) throw invalid(label, `是硬切（cut），时长必须是 0，现在是 ${durationMs} 毫秒。`);
		return null;
	}
	const durationUs = Math.round(durationMs * 1e3);
	if (durationUs <= 0) throw invalid(label, `时长必须大于 0 毫秒，现在是 ${durationMs} 毫秒。`);
	return {
		type,
		durationUs
	};
}
var ms = (us) => Math.round(us / 1e3);
/**
* 每个转场都要放得下：**时长不超过两侧片段裁剪后各自的长度，相邻两个转场不重叠**。
*
* 按最保守的占用模型算：一个转场最多吃掉前后两段各自与转场等长的一截（剪映实际是居中各吃
* 一半还是整段吃，只有真机能证实；按保守模型放行的，在任何一种模型下都放得下）。于是对每一段
* 都要求「进场转场 + 出场转场 ≤ 这一段的长度」—— 只有一侧有转场时就是「转场 ≤ 长度」。
* 违反就拒：导出层不替写入方改时长。
*
* `plan.ts` 在下载之前用已知的裁剪长度调一次（出点为 null 的段长度未知，跳过）；
* `build-draft.ts` 在探针之后用夹取过的真实长度再调一次，那一次是最终裁决。
*/
function assertTransitionsFit(segments) {
	segments.forEach((segment, index) => {
		const incoming = index > 0 ? segments[index - 1]?.transitionOut ?? null : null;
		const outgoing = index < segments.length - 1 ? segment.transitionOut ?? null : null;
		if (segment.durUs === null || !incoming && !outgoing) return;
		const inUs = incoming?.durationUs ?? 0;
		const outUs = outgoing?.durationUs ?? 0;
		if (inUs + outUs <= segment.durUs) return;
		const previous = segments[index - 1]?.title ?? "";
		const next = segments[index + 1]?.title ?? "";
		if (incoming && inUs > segment.durUs) throw invalid(previous, `长 ${ms(inUs)} 毫秒，比下一段「${segment.title}」裁剪后的长度（${ms(segment.durUs)} 毫秒）还长，剪映放不下。请缩短转场或加长片段。`);
		if (outgoing && outUs > segment.durUs) throw invalid(segment.title, `长 ${ms(outUs)} 毫秒，比这一段裁剪后的长度（${ms(segment.durUs)} 毫秒）还长，剪映放不下。请缩短转场或加长片段。`);
		throw new JianyingExportError("invalid-transition", `片段「${segment.title}」前后两个转场（与「${previous}」之间 ${ms(inUs)} 毫秒、与「${next}」之间 ${ms(outUs)} 毫秒）加起来超过了它裁剪后的长度（${ms(segment.durUs)} 毫秒），两个转场会重叠。请缩短转场或加长片段。`, segment.title);
	});
}
//#endregion
//#region apps/web/libs/jianying/build-draft.ts
/**
* 一个剪映工程的计划 + 探针结果 → 这个工程草稿包的 10 个文件（内容，不写盘）。
*
* 一次导出拆成几个工程（按集 / 单工程）在 `projects.ts`；这里只管**一个**工程、一条主视频轨。
* 从前按集导出时会在一个工程里塞 N 条时间线（`Timelines/project.json`），已经删掉 ——
* 现在每集是一个独立的剪映工程，各自一份完整的 10 个文件。
*
* 纯函数，不读盘、不发请求、不碰 window：草稿 JSON 的正确性就是这个包的全部价值，
* 而它能被 vitest 逐字节断言的前提就是这条纪律。必须在素材下完之后调用
* ——`facts` 里的 `durationUs` / `width` / `height` 是探针读出来的真值。
*
* **单位**（规格 §2.4，最容易错的地方）：
*   · VideoCutClip 是**毫秒**，plan.ts 已经换算成微秒进 JianyingPlannedSegment；
*   · 草稿 JSON 的时间轴全是**微秒**；
*   · create_time / tm_draft_* 是**微秒纪元** = Date.now() * 1000；
*   · draft_settings（INI）是**秒**；
*   · draft_timeline_materials_size_ 是**字节**，按去重后的文件求和（不去重会翻倍）。
*
* **素材路径是绝对路径**，由调用方选定的草稿根拼出来（`draftRoot`）。剪映只认绝对路径，
* 详见 `assetPathFor` 上面那段。
*/
function requireFact(facts, segment) {
	const fact = facts.get(segment.assetKey);
	if (!fact) throw new JianyingExportError("clip-out-of-range", `片段「${segment.title}」的素材没有被成功下载或探测，草稿无法生成。`, segment.title);
	return fact;
}
/**
* `materials.videos[].path` 写什么：**目标机上的绝对路径**
* `<草稿根><sep><草稿文件夹名><sep>assets<sep>video<sep><文件名>`。
*
* 从前这里写的是包内相对路径（`assets/video/001_xxxxxxxx.mp4`），推理是「浏览器决定不了
* 下载与解压的位置，猜绝对路径必然是错的」—— 推理没错，交付的却是一个 100% 不能用的包：
* 用户机器上的实证是，相对路径的草稿打开后时间线上有片段、文件名和时长都对，但预览全黑、
* 右键片段连菜单都弹不出来（剪映的「素材离线」态连自救入口都没有，`zipRelinkHint` 从前
* 教的「右键→链接媒体」那条路根本走不通）。同一台机器上绝对路径的三份草稿全都能用。
* `##_draftpath_placeholder_<UUID>_##` 那个「可移植占位符」在这五份里一次都没出现。
*
* 所以结论反过来了：**不猜，问**。草稿根由用户在项目设置里登记、导出时显式选中并确认，
* 沿 `BuildDraftContext.draftRoot` 传进来。用户解压到别处就是打不开 —— 那是当面的、
* 一句话说得清的失败（`zipGuideDetail` / `zipRelinkHint` 就写这句），比一份静悄悄全黑的
* 草稿好得多。
*/
function assetPathFor(draftRoot, draftDir, asset) {
	return joinDraftPath(draftRoot, draftDir, asset.relPath);
}
function buildJianyingDraftFiles(plan, facts, ctx) {
	const built = buildSingleTimelineDraftFiles(plan, facts, ctx);
	for (const key of Object.keys(built.files)) if (!isSafeDraftRelPath(key)) throw new JianyingExportError("clip-out-of-range", `草稿包里出现了非法的文件名「${key}」，导出已中止。`);
	return built;
}
/**
* 用探针夹过的**真实**长度再核一遍转场放不放得下（规划阶段出点为 null 的段还不知道长度），
* 然后给每个带转场的段造一条转场素材、挂到它的 extra_material_refs 上。最后一段的转场恒被忽略。
*/
function buildTransitions(plan, segments, ctx) {
	const planned = plan.segments.map((segment, index) => index < plan.segments.length - 1 ? segment.transitionOut ?? null : null);
	if (!planned.some(Boolean)) return [];
	assertTransitionsFit(plan.segments.map((segment, index) => ({
		title: segment.title,
		durUs: segments[index].target_timerange.duration,
		transitionOut: planned[index]
	})));
	const materials = [];
	planned.forEach((transition, index) => {
		if (!transition) return;
		const meta = Object.hasOwn(JIANYING_TRANSITIONS, transition.type) ? JIANYING_TRANSITIONS[transition.type] : void 0;
		if (!meta) throw new JianyingExportError("invalid-transition", `片段「${plan.segments[index].title}」的转场类型「${transition.type}」不在转场表里，草稿已中止生成。`, plan.segments[index].title);
		const material = buildTransitionMaterial({
			...meta,
			durationUs: transition.durationUs,
			newHexId: ctx.newHexId
		});
		materials.push(material);
		segments[index].extra_material_refs.push(material.id);
	});
	return materials;
}
/** 叠在一起超过上限、没写进草稿的字幕 → 一句给人看的提醒（点名时间轨上最早的那一条）。 */
function droppedSubtitlesWarning(draftName, dropped) {
	const first = dropped.reduce((earliest, cue) => cue.startUs < earliest.startUs ? cue : earliest);
	const chars = Array.from(first.text);
	const text = chars.length > 20 ? `${chars.slice(0, 20).join("")}…` : first.text;
	return `工程「${draftName}」里同一时刻叠在一起的字幕超过 4 条（字幕轨最多 4 条，再多会被推出画面），多出的 ${dropped.length} 条没有写进草稿；最早的一条在时间轨 ${(first.startUs / 1e6).toFixed(1)} 秒处：「${text}」。`;
}
/**
* 字幕 → 文本轨。按每段**探针夹过的真实**入出点截取（`source_timerange`），加上这一段在时间轨上
* 的起点换算成时间轨时间；裁完不足一帧的不写。一个能显示的字幕都没有就返回空 —— 不建文本轨，
* 也一个 id 都不多用。同一时刻重叠的字幕分到下一条文本轨，每多一条轨在画面上上移一行（不叠字）；
* 最多 `JIANYING_MAX_SUBTITLE_TRACKS` 条轨，要第 5 条轨才放得下的字幕不写，记进 `warnings`。
*/
function buildSubtitleTracks(plan, segments, fps, ctx) {
	if (!plan.segments.some((segment) => segment.subtitles?.length)) return {
		tracks: [],
		texts: [],
		warnings: []
	};
	const oneFrameUs = Math.ceil(1e6 / (fps > 0 ? fps : 30));
	const allLanes = layoutSubtitleTracks(plan.segments.map((segment, index) => ({
		sourceStartUs: segments[index].source_timerange.start,
		durUs: segments[index].source_timerange.duration,
		targetStartUs: segments[index].target_timerange.start,
		subtitles: segment.subtitles
	})), oneFrameUs);
	const lanes = allLanes.slice(0, 4);
	const dropped = allLanes.slice(4).flat();
	const warnings = dropped.length > 0 ? [droppedSubtitlesWarning(plan.draftName, dropped)] : [];
	const texts = [];
	const tracks = [];
	let renderIndex = SUBTITLE_RENDER_INDEX_BASE;
	for (const [laneIndex, lane] of lanes.entries()) {
		const laneSegments = [];
		for (const cue of lane) {
			const material = buildSubtitleMaterial({
				text: cue.text,
				newHexId: ctx.newHexId
			});
			texts.push(material);
			laneSegments.push(buildTextSegment({
				materialId: material.id,
				targetStartUs: cue.startUs,
				durationUs: cue.durUs,
				renderIndex,
				lane: laneIndex,
				newHexId: ctx.newHexId
			}));
			renderIndex += 1;
		}
		tracks.push({
			attribute: 0,
			flag: 0,
			id: ctx.newHexId(),
			is_default_name: true,
			name: "",
			segments: laneSegments,
			type: "text"
		});
	}
	return {
		tracks,
		texts,
		warnings
	};
}
function buildSingleTimelineDraftFiles(plan, facts, ctx) {
	const draftRoot = normalizeDraftRootPath(ctx.draftRoot);
	const rootIssue = checkDraftRootPath(draftRoot);
	if (rootIssue) throw new JianyingExportError("invalid-draft-root", rootIssue === "empty" ? "没有选择剪映草稿目录，草稿里的素材路径无从写起。请先在项目设置里登记一个草稿目录。" : `剪映草稿目录「${ctx.draftRoot}」不是绝对路径，剪映只认绝对路径。`);
	const pathSep = draftRootPathSep(draftRoot);
	const draftDir = plan.draftName;
	const draftFold = joinDraftPath(draftRoot, draftDir);
	const assetByKey = new Map(plan.assets.map((asset) => [asset.key, asset]));
	const resolved = plan.segments.map((segment) => ({
		segment,
		fact: requireFact(facts, segment)
	}));
	const canvas = canvasFromMeasurements(resolved.map(({ fact }) => ({
		width: fact.width,
		height: fact.height
	})), ctx.canvasRatio ?? null);
	const draftId = ctx.newUpperId();
	const draft = buildEmptyDraft(canvas, draftId, pathSep);
	const videos = [];
	const speeds = [];
	const segments = [];
	let cursorUs = 0;
	for (const { segment, fact } of resolved) {
		const asset = assetByKey.get(segment.assetKey);
		if (!asset) throw new JianyingExportError("clip-out-of-range", `片段「${segment.title}」引用了一个不在导出计划里的素材，草稿无法生成。`, segment.title);
		const width = fact.width > 0 ? fact.width : canvas.width;
		const height = fact.height > 0 ? fact.height : canvas.height;
		if (segment.inUs >= fact.durationUs) throw new JianyingExportError("clip-out-of-range", `片段「${segment.title}」的起点在 ${Math.round(segment.inUs / 1e3)} 毫秒处，已经超出源视频的长度（${Math.round(fact.durationUs / 1e3)} 毫秒）；素材可能被重新生成过，请在时间线上重新裁剪后再导出。`, segment.title);
		const maxStartUs = Math.max(0, fact.durationUs - MIN_JIANYING_SEGMENT_US);
		const inUs = Math.min(segment.inUs, maxStartUs);
		const durUs = (segment.outUs === null ? fact.durationUs : Math.min(segment.outUs, fact.durationUs)) - inUs;
		if (durUs < 1e5) throw new JianyingExportError("clip-out-of-range", `片段「${segment.title}」的裁剪区间落在了源视频之外（源长 ${Math.round(fact.durationUs / 1e3)} 毫秒），剪映草稿放不下它。`, segment.title);
		const material = buildVideoMaterial({
			path: assetPathFor(draftRoot, draftDir, asset),
			fileName: asset.assetName,
			durationUs: fact.durationUs,
			width,
			height,
			newHexId: ctx.newHexId
		});
		const built = buildVideoSegment({
			materialId: material.id,
			targetStartUs: cursorUs,
			sourceStartUs: inUs,
			durationUs: durUs,
			...segment.volume === void 0 ? {} : { volume: segment.volume },
			newHexId: ctx.newHexId
		});
		videos.push(material.json);
		speeds.push(built.speed);
		segments.push(built.segment);
		cursorUs += durUs;
	}
	draft.materials.videos = videos;
	draft.materials.speeds = speeds;
	draft.duration = cursorUs;
	draft.create_time = ctx.now.getTime() * 1e3;
	draft.update_time = draft.create_time;
	draft.name = plan.draftName;
	draft.tracks = [{
		attribute: 0,
		flag: 0,
		id: ctx.newHexId(),
		is_default_name: false,
		name: JIANYING_MAIN_TRACK_NAME,
		segments,
		type: "video"
	}];
	for (let i = 0; i < segments.length; i += 1) {
		const range = segments[i].source_timerange;
		const material = videos[i];
		if (range.start + range.duration > material.duration) throw new JianyingExportError("clip-out-of-range", `片段「${plan.segments[i]?.title ?? i + 1}」裁剪后超出了素材长度，草稿已中止生成。`, plan.segments[i]?.title);
	}
	draft.materials.transitions = buildTransitions(plan, segments, ctx);
	const subtitles = buildSubtitleTracks(plan, segments, canvas.fps, ctx);
	if (subtitles.tracks.length > 0) {
		draft.materials.texts = subtitles.texts;
		draft.tracks.push(...subtitles.tracks);
	}
	let totalBytes = 0;
	for (const asset of plan.assets) {
		const fact = facts.get(asset.key);
		if (fact && Number.isFinite(fact.bytes)) totalBytes += fact.bytes;
	}
	const nowMs = ctx.now.getTime();
	const draftText = draftJsonText(draft);
	const files = {
		[DRAFT_CONTENT_FILE]: draftText,
		[DRAFT_INFO_FILE]: draftText,
		...buildSidecarFiles({
			draftDir: draftFold,
			draftRoot,
			draftName: plan.draftName,
			draftId,
			durationUs: cursorUs,
			bytes: totalBytes,
			canvas,
			pathSep,
			nowMs,
			newUpperId: ctx.newUpperId
		})
	};
	return {
		files,
		writeOrder: [...Object.keys(files).filter((name) => name !== DRAFT_META_FILE), DRAFT_META_FILE],
		canvas,
		totalDurationUs: cursorUs,
		totalBytes,
		...subtitles.warnings.length > 0 ? { warnings: subtitles.warnings } : {}
	};
}
Object.freeze({
	version: 1,
	clips: []
});
//#endregion
//#region apps/web/libs/upload/assethub-file-id.ts
/**
* AssetHub object URLs carry their own identity.
*
* Production objects are `https://{cdn|file}.echojoy.cn/files/{YYYY-MM-DD}/{uuid}.{ext}`:
* the basename IS the AssetHub file id and the extension IS the media kind. Both
* facts are load-bearing in production already — `/api/tools/files/{id}/preview`
* is reachable from a stored URL alone because canvas nodes persist URLs and
* never file ids — and both hold across every row of `cloud_media_publications`
* (29,774 rows, zero id/basename mismatches).
*
* Deriving the identity from the URL is what lets a caller that needs a file id
* skip re-uploading bytes that are already in AssetHub. Isomorphic on purpose:
* the canvas display layer (client) and the gateway-result persistence path
* (server) must agree on the answer, so neither React nor node builtins belong
* in here.
*/
var ASSETHUB_HOSTS = /* @__PURE__ */ new Set(["cdn.echojoy.cn", "file.echojoy.cn"]);
var UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
var OBJECT_PATH_RE = /^\/files\/[^/]+\/([^/.]+)\.([^./]+)$/;
function assetHubObjectPath(url) {
	if (!url) return void 0;
	let parsed;
	try {
		parsed = new URL(url);
	} catch {
		return;
	}
	if (parsed.protocol !== "https:") return void 0;
	if (!ASSETHUB_HOSTS.has(parsed.hostname.toLowerCase())) return void 0;
	return parsed.pathname.match(OBJECT_PATH_RE) ?? void 0;
}
/**
* The AssetHub file UUID a stored URL points at, or undefined for anything else
* — a foreign host, a non-UUID basename, or a `/thumbnails/` URL that is already
* a derived rendition rather than an original.
*/
function assetHubFileId(url) {
	const id = assetHubObjectPath(url)?.[1];
	return id && UUID_RE.test(id) ? id.toLowerCase() : void 0;
}
//#endregion
//#region apps/web/libs/jianying/plan.ts
/**
* 导出前的规划（一个剪映工程）：去重、命名、预检闸（空时间线、段数、容器、独立配音、裁剪区间、
* 转场），并把片段上的转场 / 字幕 / 音量带进计划。纯函数，不发一个字节的请求。
*
* 闸放在这里而不是放在下载之后，理由只有一条：**拒就要拒在花钱之前**。
* 一个 .webm 片段应该在用户点下按钮的那一瞬间被拒掉，而不是等 300MB 下完了才说不行。
*/
/** 报错文案里指代某一段用的名字；title 可能是空串。 */
function clipLabel(clip, index) {
	return (typeof clip?.title === "string" ? clip.title.trim() : "") || `第 ${index + 1} 段`;
}
/**
* 去重键。AssetHub 的对象地址自带身份（basename 就是文件 id），先按它归一化，
* 免得同一个文件因为签名参数或 CDN 域名不同被当成两份下两遍。
* 不是 AssetHub 的地址就用 src 全串——那时我们对它的身份一无所知，宁可多下一份。
*/
function assetKeyForUrl(url) {
	const fileId = assetHubFileId(url);
	return fileId ? `assethub:${fileId}` : url;
}
function assertSupportedSource(clip, index) {
	const src = typeof clip?.src === "string" ? clip.src : "";
	const label = clipLabel(clip, index);
	if (!/^https?:\/\//iu.test(src)) throw new JianyingExportError("unsupported-container", `片段「${label}」的视频地址不是可下载的 http(s) 地址，无法导出到剪映。`, label);
	if (!extensionFromUrl(src)) throw new JianyingExportError("unsupported-container", `片段「${label}」的视频格式剪映打不开，只支持 ${[...JIANYING_VIDEO_EXTENSIONS].join(" / ")}。`, label);
}
function assertNoSeparateAudio(clip, index) {
	if (!(typeof clip?.audioUrl === "string" ? clip.audioUrl.trim() : "")) return;
	const label = clipLabel(clip, index);
	throw new JianyingExportError("separate-audio", `片段「${label}」挂了一条独立配音，剪映草稿导出还不支持多轨；请先在编辑器里把它合成进视频再导出。`, label);
}
/** 片段音量（线性增益）。只认非负有限数（0 = 静音），其余按原声 1 —— 与存盘时的规整一致。 */
function plannedVolume(raw) {
	return typeof raw === "number" && Number.isFinite(raw) && raw >= 0 ? raw : 1;
}
/** 返回裁剪区间（微秒）。区间不合法就拒，绝不静默改成整段。 */
function trimRangeUs(clip, index) {
	const label = clipLabel(clip, index);
	const inMs = Number(clip?.inMs ?? 0);
	const rawOut = clip?.outMs;
	const outMs = rawOut === null || rawOut === void 0 ? null : Number(rawOut);
	const refuse = (why) => new JianyingExportError("clip-out-of-range", `片段「${label}」${why}`, label);
	if (!Number.isFinite(inMs) || inMs < 0) throw refuse("的起点不是一个合法的时间。");
	if (outMs !== null) {
		if (!Number.isFinite(outMs)) throw refuse("的终点不是一个合法的时间。");
		if (outMs - inMs < 100) throw refuse(`裁得太短了（不足 100 毫秒），剪映会把它当成空片段。`);
	}
	return {
		inUs: Math.round(inMs * 1e3),
		outUs: outMs === null ? null : Math.round(outMs * 1e3)
	};
}
/**
* 一个剪映工程的片段 → 这个工程的导出计划。违反任何一道闸都抛 `JianyingExportError`，
* `message` 是可以直接显示给用户的中文原因，`clipTitle` 指出是哪一段。
*
* 一次导出有几个工程、每个工程是哪些片段，由 `projects.ts` 的 `planJianyingProjects` 决定，
* 它对每个工程各调一次这里 —— 所以 200 段上限是**每个工程**的上限。
*
* `hash` 注入（sha1 前 8 位）：命名必须可复现，测试才能断言 `001_a3f91c2e.mp4`。
* `projectLabel`：按集导出时的工程标签（`EP03` / `其他`），只用来让超限文案点名是哪一集。
*/
function planJianyingDraft(input) {
	const clips = input.clips ?? [];
	if (clips.length === 0) throw new JianyingExportError("empty-timeline", "时间线上还没有片段，先把视频拖到时间线上再导出剪映草稿。");
	if (clips.length > 200) throw new JianyingExportError("too-many-clips", input.projectLabel ? `「${input.projectLabel}」有 ${clips.length} 个片段，超过一个剪映工程的上限 200 个，请把这一集拆开导出。` : `时间线有 ${clips.length} 个片段，超过一次导出的上限 200 个，请分批导出。`);
	const assetsByKey = /* @__PURE__ */ new Map();
	const assets = [];
	const segments = [];
	clips.forEach((clip, index) => {
		assertSupportedSource(clip, index);
		assertNoSeparateAudio(clip, index);
		const { inUs, outUs } = trimRangeUs(clip, index);
		const label = clipLabel(clip, index);
		const transitionOut = index < clips.length - 1 ? planTransitionOut(clip?.transitionOut, label) : null;
		const subtitles = planSubtitles(clip?.subtitles);
		const volume = plannedVolume(clip?.volume);
		const key = assetKeyForUrl(clip.src);
		let asset = assetsByKey.get(key);
		if (!asset) {
			const assetName = assetFileName(assets.length + 1, key, clip.src, input.hash);
			asset = {
				key,
				url: clip.src,
				assetName,
				relPath: `${JIANYING_ASSET_DIR}/${assetName}`,
				clipTitles: []
			};
			assetsByKey.set(key, asset);
			assets.push(asset);
		}
		asset.clipTitles.push(label);
		segments.push({
			clipId: typeof clip.id === "string" && clip.id ? clip.id : `clip-${index + 1}`,
			title: label,
			assetKey: key,
			inUs,
			outUs,
			...transitionOut ? { transitionOut } : {},
			...subtitles.length > 0 ? { subtitles } : {},
			...volume === 1 ? {} : { volume }
		});
	});
	assertTransitionsFit(segments.map((segment) => ({
		title: segment.title,
		durUs: segment.outUs === null ? null : segment.outUs - segment.inUs,
		transitionOut: segment.transitionOut
	})));
	return {
		draftName: safeName(input.draftName),
		assets,
		segments
	};
}
//#endregion
//#region apps/web/libs/jianying/projects.ts
/**
* 剪映导出的「工程」层：一次导出拆成几个剪映工程、每个工程叫什么、各自的计划。
*
* **界面与 CLI 共用的纯函数入口**（不碰 window / 网络 / 文件系统，vitest 的 node 环境里
* 整段可断言）：
*
*   ① `planJianyingProjects({ clips, projectName, layout?, now, hash })`
*        时间线片段 → 各工程的导出计划（`JianyingExportPlan`）。所有预检闸都在这里跑完
*        （每个工程各自的 200 段上限、容器、独立配音、裁剪区间、转场），一个字节都不下；
*        片段上的转场 / 字幕 / 音量随之带进计划。
*   ② `buildJianyingProjects(exportPlan, facts, ctx)`
*        计划 + 素材探针事实 → 每个工程的草稿文件（10 个文件的内容，不写盘）。
*        `facts` 以素材身份（`JianyingPlannedAsset.key`）为键，跨工程共用一份。
*   ③ 素材的三道共用件（文件末尾），页面与 CLI 用同一份，产物与拒绝口径才一致：
*        `assetDigest` —— 素材文件名里的 8 位摘要，作 ① 的 `hash` 传入；
*        `assertTrustedJianyingAssets(plan)` / `isTrustedJianyingAssetUrl(url)` —— 素材地址白名单，
*        下第一个字节之前判；
*        `checkJianyingProjectBytes(bytes, label)` —— 单个工程的素材总量闸（3 GiB）。
*
* 单个工程的草稿 JSON 在 `build-draft.ts`（`buildJianyingDraftFiles`）；页面那条路
* （每个工程边下素材边打包、一个工程一个 zip）在 `export-flow.ts`，它按工程逐个调这几层。
*
* **怎么分工程**（产品决策，2026-09-23）：
*   · 有任何一段标题命中 `epNN` → 按集，每集一个独立工程（`<剧名>_EP01_<时间戳>`）；
*     没有集号的片段不丢，单独成一个「其他」工程（`<剧名>_其他_<时间戳>`）；
*   · 一段都没命中（广告片、MV）→ 单工程（`<剧名>_<时间戳>`）；
*   · 调用方可以显式指定 `layout` 覆盖上面的推断（界面上的「按集 / 单工程」开关）。
* 从前的做法是「一个工程里放 N 条时间线」（`Timelines/project.json`），剪映里一集一集地
* 切时间线既难找也难交付，已经删掉。
*/
/** 单工程时那个唯一工程的键。 */
var SINGLE_PROJECT_KEY = "all";
/** 标题是 agent/用户可控的任意值，可能根本不是字符串。 */
function titleOf(clip) {
	return typeof clip?.title === "string" ? clip.title : "";
}
/** 按片段标题推断工程组织方式：有任何一段带集号就按集，一段都没有就单工程。 */
function detectJianyingLayout(clips) {
	return (clips ?? []).some((clip) => episodeKey(titleOf(clip)) !== "unknown") ? "episodes" : "single";
}
/**
* 按组织方式把时间线分成工程。按集时工程顺序与剪辑器的集选项卡一致（集号从小到大，
* 「其他」最后）；每个工程内部保持片段在时间线上的相对顺序（裁剪、顺序一律不动）。
*/
function partitionJianyingProjects(clips, layout) {
	const list = [...clips ?? []];
	if (layout === "single") return [{
		key: SINGLE_PROJECT_KEY,
		label: null,
		clips: list
	}];
	const groups = /* @__PURE__ */ new Map();
	for (const clip of list) {
		const key = episodeKey(titleOf(clip));
		const group = groups.get(key);
		if (group) group.push(clip);
		else groups.set(key, [clip]);
	}
	return episodeKeys(list.map((clip) => ({ title: titleOf(clip) }))).map((key) => ({
		key,
		label: key === "unknown" ? JIANYING_OTHER_PROJECT_LABEL : key,
		clips: groups.get(key) ?? []
	}));
}
/**
* 入口 ①：时间线 → 各工程的导出计划。每个工程各跑一遍 `planJianyingDraft` 的全部闸，
* 任何一个工程不合格就整单拒（抛 `JianyingExportError`），拒在下第一个字节之前。
*
* `now` 只用来给工程起名（时间戳后缀），同一批工程共用同一个时间戳。
*/
function planJianyingProjects(input) {
	const clips = input.clips ?? [];
	const layout = input.layout ?? detectJianyingLayout(clips);
	const groups = partitionJianyingProjects(clips, layout);
	if (groups.length === 0) planJianyingDraft({
		clips: [],
		draftName: "",
		hash: input.hash
	});
	return {
		layout,
		projects: groups.map((group) => ({
			key: group.key,
			label: group.label,
			plan: planJianyingDraft({
				clips: group.clips,
				draftName: draftFolderName(input.projectName, input.now, group.label),
				hash: input.hash,
				projectLabel: group.label
			})
		}))
	};
}
/**
* 入口 ②：计划 + 素材事实 → 每个工程各自完整的草稿文件（`draft_content.json` /
* `draft_info.json` / `draft_meta_info.json` 与 7 个附属文件）。每个工程的素材路径都指向
* `<草稿根>/<该工程文件夹>/assets/video/…`，所以每个工程文件夹都要自带它用到的素材。
*/
function buildJianyingProjects(exportPlan, facts, ctx) {
	return exportPlan.projects.map((project) => ({
		...project,
		built: buildJianyingDraftFiles(project.plan, facts, ctx)
	}));
}
/**
* 素材名里的 8 位摘要，作 `planJianyingProjects` 的 `hash` 传入。页面导出（`export-flow.ts`）
* 用的就是它；别的调用方（CLI）也传它，素材文件名才与页面导出的逐字节一致。
*
* 规格写的是「sha1 前 8 位」，但 `planJianyingDraft` 要的是一个**同步**函数，而浏览器里唯一的
* sha1 是异步的 `crypto.subtle` —— 换成同步的 FNV-1a。这不会削弱任何东西：摘要只负责「同一次
* 导出里两个素材不撞名」，而文件名前面还有一个唯一的三位序号（`001_`/`002_`），摘要撞了文件名
* 也照样不撞。
*/
function assetDigest(value) {
	let hash = 2166136261;
	for (let i = 0; i < value.length; i += 1) {
		hash ^= value.charCodeAt(i);
		hash = Math.imul(hash, 16777619) >>> 0;
	}
	return hash.toString(16).padStart(8, "0");
}
var JIANYING_ASSET_HOSTS_EXACT = /* @__PURE__ */ new Set(["cdn.echojoy.cn", "file.echojoy.cn"]);
var JIANYING_ASSET_HOST_SUFFIXES = [".myqcloud.com", ".tos-cn-beijing.volces.com"];
function normalizeHost(host) {
	return (host.startsWith("[") && host.endsWith("]") ? host.slice(1, -1) : host).toLowerCase().replace(/\.$/u, "");
}
/** 不带 `node:net`：IPv4 字面量与方括号 IPv6 各判一次就够（域名里不会出现这两种形状）。 */
function isIpLiteral(hostname) {
	if (/^\d{1,3}(?:\.\d{1,3}){3}$/u.test(hostname)) return true;
	return hostname.includes(":");
}
/** https + 无 userinfo + 非 IP/localhost/.local + 命中白名单，四条全过才算可信。 */
function isTrustedJianyingAssetUrl(value) {
	let url;
	try {
		url = new URL(value);
	} catch {
		return false;
	}
	if (url.protocol !== "https:") return false;
	if (url.username || url.password) return false;
	const host = normalizeHost(url.hostname);
	if (!host || host === "localhost" || host.endsWith(".local")) return false;
	if (isIpLiteral(host)) return false;
	return JIANYING_ASSET_HOSTS_EXACT.has(host) || JIANYING_ASSET_HOST_SUFFIXES.some((suffix) => host.endsWith(suffix) && host.length > suffix.length);
}
/** 预检：一个工程计划里的素材地址全部过白名单，否则整单拒（`untrusted-host`），点名第一段用到它的片段。 */
function assertTrustedJianyingAssets(plan) {
	for (const asset of plan.assets) {
		if (isTrustedJianyingAssetUrl(asset.url)) continue;
		const title = asset.clipTitles[0] ?? asset.assetName;
		throw new JianyingExportError("untrusted-host", `片段「${title}」的素材来自不受信任的地址，客户端不会去下载它，请重新生成或上传这段视频。`, title);
	}
}
//#endregion
export { ASSET_FILE_NAME_RE, DIRECT_FETCH_CONCURRENCY, DRAFT_META_FILE, JIANYING_ASSET_DIR, JIANYING_MAX_CLIPS, JIANYING_OTHER_PROJECT_LABEL, JianyingExportError, MEDIA_FETCH_ATTEMPTS, UNKNOWN_EPISODE, assertTrustedJianyingAssets, assetDigest, buildJianyingProjects, checkDraftRootPath, detectJianyingLayout, draftRootKey, episodeKey, episodeKeys, isSafeDraftRelPath, isTrustedJianyingAssetUrl, newHexId, newUpperId, planJianyingProjects, safeName, sortDraftRootsByRecentUse };
